// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: key_rotation.proto

package keyrotation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyRotationNotifyService_NotifyKeyRolled_FullMethodName = "/KeyRotationNotifyService/NotifyKeyRolled"
)

// KeyRotationNotifyServiceClient is the client API for KeyRotationNotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyRotationNotifyServiceClient interface {
	NotifyKeyRolled(ctx context.Context, in *NotifyKeyRolledRequest, opts ...grpc.CallOption) (*NotifyKeyRolledResponse, error)
}

type keyRotationNotifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyRotationNotifyServiceClient(cc grpc.ClientConnInterface) KeyRotationNotifyServiceClient {
	return &keyRotationNotifyServiceClient{cc}
}

func (c *keyRotationNotifyServiceClient) NotifyKeyRolled(ctx context.Context, in *NotifyKeyRolledRequest, opts ...grpc.CallOption) (*NotifyKeyRolledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyKeyRolledResponse)
	err := c.cc.Invoke(ctx, KeyRotationNotifyService_NotifyKeyRolled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyRotationNotifyServiceServer is the server API for KeyRotationNotifyService service.
// All implementations must embed UnimplementedKeyRotationNotifyServiceServer
// for forward compatibility.
type KeyRotationNotifyServiceServer interface {
	NotifyKeyRolled(context.Context, *NotifyKeyRolledRequest) (*NotifyKeyRolledResponse, error)
	mustEmbedUnimplementedKeyRotationNotifyServiceServer()
}

// UnimplementedKeyRotationNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyRotationNotifyServiceServer struct{}

func (UnimplementedKeyRotationNotifyServiceServer) NotifyKeyRolled(context.Context, *NotifyKeyRolledRequest) (*NotifyKeyRolledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyKeyRolled not implemented")
}
func (UnimplementedKeyRotationNotifyServiceServer) mustEmbedUnimplementedKeyRotationNotifyServiceServer() {
}
func (UnimplementedKeyRotationNotifyServiceServer) testEmbeddedByValue() {}

// UnsafeKeyRotationNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyRotationNotifyServiceServer will
// result in compilation errors.
type UnsafeKeyRotationNotifyServiceServer interface {
	mustEmbedUnimplementedKeyRotationNotifyServiceServer()
}

func RegisterKeyRotationNotifyServiceServer(s grpc.ServiceRegistrar, srv KeyRotationNotifyServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyRotationNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyRotationNotifyService_ServiceDesc, srv)
}

func _KeyRotationNotifyService_NotifyKeyRolled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyKeyRolledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyRotationNotifyServiceServer).NotifyKeyRolled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyRotationNotifyService_NotifyKeyRolled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyRotationNotifyServiceServer).NotifyKeyRolled(ctx, req.(*NotifyKeyRolledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyRotationNotifyService_ServiceDesc is the grpc.ServiceDesc for KeyRotationNotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyRotationNotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KeyRotationNotifyService",
	HandlerType: (*KeyRotationNotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyKeyRolled",
			Handler:    _KeyRotationNotifyService_NotifyKeyRolled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key_rotation.proto",
}
