// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: key_rotation.proto

package keyrotation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyKeyRolledRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PreviousKid         string                 `protobuf:"bytes,1,opt,name=previousKid,proto3" json:"previousKid,omitempty"`
	CurrentKid          string                 `protobuf:"bytes,2,opt,name=currentKid,proto3" json:"currentKid,omitempty"`
	RolledAt            string                 `protobuf:"bytes,3,opt,name=rolledAt,proto3" json:"rolledAt,omitempty"`
	CurrentPublicKeyPem string                 `protobuf:"bytes,4,opt,name=currentPublicKeyPem,proto3" json:"currentPublicKeyPem,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NotifyKeyRolledRequest) Reset() {
	*x = NotifyKeyRolledRequest{}
	mi := &file_key_rotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyKeyRolledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyKeyRolledRequest) ProtoMessage() {}

func (x *NotifyKeyRolledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_rotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyKeyRolledRequest.ProtoReflect.Descriptor instead.
func (*NotifyKeyRolledRequest) Descriptor() ([]byte, []int) {
	return file_key_rotation_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyKeyRolledRequest) GetPreviousKid() string {
	if x != nil {
		return x.PreviousKid
	}
	return ""
}

func (x *NotifyKeyRolledRequest) GetCurrentKid() string {
	if x != nil {
		return x.CurrentKid
	}
	return ""
}

func (x *NotifyKeyRolledRequest) GetRolledAt() string {
	if x != nil {
		return x.RolledAt
	}
	return ""
}

func (x *NotifyKeyRolledRequest) GetCurrentPublicKeyPem() string {
	if x != nil {
		return x.CurrentPublicKeyPem
	}
	return ""
}

type NotifyKeyRolledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyKeyRolledResponse) Reset() {
	*x = NotifyKeyRolledResponse{}
	mi := &file_key_rotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyKeyRolledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyKeyRolledResponse) ProtoMessage() {}

func (x *NotifyKeyRolledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_rotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyKeyRolledResponse.ProtoReflect.Descriptor instead.
func (*NotifyKeyRolledResponse) Descriptor() ([]byte, []int) {
	return file_key_rotation_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyKeyRolledResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_key_rotation_proto protoreflect.FileDescriptor

var file_key_rotation_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b,
	0x65, 0x79, 0x52, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4b, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x4b, 0x69,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4b, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x12, 0x30, 0x0a,
	0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x50, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x50, 0x65, 0x6d, 0x22,
	0x33, 0x0a, 0x17, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x6c, 0x6c,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x62, 0x0a, 0x18, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x46, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x6c,
	0x6c, 0x65, 0x64, 0x12, 0x17, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b, 0x65, 0x79, 0x52,
	0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x4b, 0x65, 0x79, 0x52, 0x6f, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x0a, 0x12, 0x6f, 0x72, 0x67, 0x2e,
	0x6e, 0x6f, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x62, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x10,
	0x4b, 0x65, 0x79, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x0f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_key_rotation_proto_rawDescOnce sync.Once
	file_key_rotation_proto_rawDescData []byte
)

func file_key_rotation_proto_rawDescGZIP() []byte {
	file_key_rotation_proto_rawDescOnce.Do(func() {
		file_key_rotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_rotation_proto_rawDesc), len(file_key_rotation_proto_rawDesc)))
	})
	return file_key_rotation_proto_rawDescData
}

var file_key_rotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_key_rotation_proto_goTypes = []any{
	(*NotifyKeyRolledRequest)(nil),  // 0: NotifyKeyRolledRequest
	(*NotifyKeyRolledResponse)(nil), // 1: NotifyKeyRolledResponse
}
var file_key_rotation_proto_depIdxs = []int32{
	0, // 0: KeyRotationNotifyService.NotifyKeyRolled:input_type -> NotifyKeyRolledRequest
	1, // 1: KeyRotationNotifyService.NotifyKeyRolled:output_type -> NotifyKeyRolledResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_rotation_proto_init() }
func file_key_rotation_proto_init() {
	if File_key_rotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_rotation_proto_rawDesc), len(file_key_rotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_rotation_proto_goTypes,
		DependencyIndexes: file_key_rotation_proto_depIdxs,
		MessageInfos:      file_key_rotation_proto_msgTypes,
	}.Build()
	File_key_rotation_proto = out.File
	file_key_rotation_proto_goTypes = nil
	file_key_rotation_proto_depIdxs = nil
}
